// Protocol to Pantry Basket Mapping
export const PROTOCOL_MAPPING = {
  // Direct matches (protocol name -> basket name)
  "ABDOMINAL PAIN": "ABDOMINAL_PAIN",
  "ABUSE REPORTING AND COMMUNITY SERVICE": "ABUSE_REPORTING_AND_COMMUNITY_SERVICE",
  "AGITATED PATIENT – EXCITED DELIRIUM SYNDROME": "AGITATED_PATIENT_–_EXCITED_DELIRIUM_SYNDROME",
  "AICD / AUTOMATIC IMPLANTABLE CARDIOVERTER / DEFIBRILLATOR": "AICD___AUTOMATIC_IMPLANTABLE_CARDIOVERTER___DEFIBRILLATOR",
  "AIRWAY MANAGEMENT": "AIRWAY_MANAGEMENT",
  "ALCOHOL INTOXICATION": "ALCOHOL_INTOXICATION",
  "ALLERGIC / SYSTEMIC REACTIONS": "ALLERGIC___SYSTEMIC_REACTIONS",
  "AMPUTATIONS": "AMPUTATIONS",
  "BACK PAIN": "BACK_PAIN",
  "BAKER ACT / MARCHMAN ACT": "BAKER_ACT___MARCHMAN_ACT",
  "BITES AND STINGS": "BITES_AND_STINGS",
  "BRADYCARDIA": "BRADYCARDIA",
  "BURNS": "BURNS",
  "CARDIAC ARREST": "CARDIAC_ARREST",
  "CHEST PAIN – STEMI": "CHEST_PAIN_STEMI",
  "CO-CN EXPOSURE": "CO-CN_EXPOSURE",
  "CRUSH INJURIES": "CRUSH_INJURIES",
  "DEATH IN FIELD": "DEATH_IN_FIELD",
  "ENTRAPMENT": "ENTRAPMENT",
  "ENVIRONMENTAL EMERGENCIES": "ENVIRONMENTAL_EMERGENCIES",
  "EPISTAXIS": "EPISTAXIS",
  "EYE INJURIES": "EYE_INJURIES",
  "FIELD BLOOD TRANSFUSION": "FIELD_BLOOD_TRANSFUSION",
  "FIELD SURGICAL AMPUTATION": "FIELD_SURGICAL_AMPUTATION",
  "FIREFIGHTER REHABILITATION": "FIREFIGHTER_REHABILITATION",
  "FRACTURES - SUSPECTED": "FRACTURES_-_SUSPECTED",
  "HEAD AND SPINAL -SUSPECTED": "HEAD_AND_SPINAL_-SUSPECTED",
  "HYPERTENSIVE EMERGENCIES": "HYPERTENSIVE_EMERGENCIES",
  "HYPOVOLEMIC SHOCK": "HYPOVOLEMIC_SHOCK",
  "IMPAIRED OR ALTERED CONSCIOUSNESS": "IMPAIRED_OR_ALTERED_CONSCIOUSNESS",
  "OB / CHILD BIRTH EMERGENCIES": "OB___CHILD_BIRTH_EMERGENCIES",
  "PAIN AND NAUSEA – VOMITING MANAGEMENT": "PAIN_AND_NAUSEA_–_VOMITING_MANAGEMENT",
  "PEPPER SPRAY EXPOSURES": "PEPPER_SPRAY_EXPOSURES",
  "POISONING / DRUG OVERDOSE": "POISONING___DRUG_OVERDOSE",
  "POST RESUSCITATION": "POST_RESUSCITATION",
  "PREGNANCY": "PREGNANCY",
  "PSYCHIATRIC EMERGENCIES": "PSYCHIATRIC_EMERGENCIES",
  "RAPE MANAGEMENT": "RAPE_MANAGEMENT",
  "RESPIRATORY EMERGENCIES": "RESPIRATORY_EMERGENCIES",
  "SEIZURES": "SEIZURES",
  "SHOCK – HYPOTENSION": "SHOCK_-_HYPOTENSION",
  "SICKLE CELL PATIENTS": "SICKLE_CELL_PATIENTS",
  "SOFT TISSUE INJURIES": "SOFT_TISSUE_INJURIES",
  "STROKE": "STROKE",
  "SYNCOPE": "SYNCOPE",
  "TACHYCARDIA": "TACHYCARDIA",
  "TASER EXPOSURES": "TASER_EXPOSURES",
  "THERAPEUTIC HYPOTHERMIA": "THERAPEUTIC_HYPOTHERMIA",
  "UNIVERSAL INITIAL ADULT PATIENT ASSESSMENT CARE": "UNIVERSAL_INITIAL_ADULT_PATIENT_ASSESSMENT_CARE",
  "VENTRICULAR ASSIST DEVICE (VAD)": "VENTRICULAR_ASSIST_DEVICE_(VAD)",
  "WATER RELATED EMERGENCIES": "WATER_RELATED_EMERGENCIES"
};

// Helper function to convert protocol name to basket name
export function getBasketName(protocolName) {
  return PROTOCOL_MAPPING[protocolName] || null;
}

// Helper function to check if protocol exists in pantry
export function hasProtocolBasket(protocolName) {
  return protocolName in PROTOCOL_MAPPING;
}